apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: guvenlik-rolebinding
subjects:
- kind: User
  name: guvenlik
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: guvenlik-role
  apiGroup: rbac.authorization.k8s.io
