apiVersion: v1
kind: List
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: readonly-view
      namespace: ns1
    subjects:
    - kind: User
      name: readonly
      apiGroup: rbac.authorization.k8s.io
    roleRef:
      kind: Role
      name: view
      apiGroup: rbac.authorization.k8s.io
