apiVersion: v1
kind: List
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: user1-admin
      namespace: ns1
    subjects:
    - kind: User
      name: user1
      apiGroup: rbac.authorization.k8s.io
    roleRef:
      kind: Role
      name: admin
      apiGroup: rbac.authorization.k8s.io
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: user2-admin
      namespace: ns2
    subjects:
    - kind: User
      name: user2
      apiGroup: rbac.authorization.k8s.io
    roleRef:
      kind: Role
      name: admin
      apiGroup: rbac.authorization.k8s.io
  # Devamını 15 kullanıcıya kadar aynı şekilde ekle...
